name: Push to Replicate

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Docker est DÉJÀ présent sur le runner GitHub
      - name: Install Cog
        run: |
          sudo curl -L https://github.com/replicate/cog/releases/latest/download/cog-linux-amd64 -o /usr/local/bin/cog
          sudo chmod +x /usr/local/bin/cog
          cog --version

      - name: Login to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: cog login

      - name: Push model to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: cog push r8.im/fabqui84/light-x
